### ISSUE TITLE
[doc] add contributing guide

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep.github.io#155]
```[tasklist]
### Tasks
- [ ] https://github.com/ast-grep/ast-grep.github.io/issues/157
- [ ] https://github.com/ast-grep/ast-grep.github.io/issues/158
- [ ] https://github.com/ast-grep/ast-grep.github.io/issues/160
- [ ] https://github.com/ast-grep/ast-grep.github.io/issues/190
- [ ] https://github.com/ast-grep/ast-grep.github.io/issues/205
```

**Comment by HerringtonDarkholme** [comment]
All completed.
